//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SupportTicketDemo.DAL.Database
{

    [Persistent(@"tblEdition")]
    public partial class Edition : XPObject
    {
        string fName;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"tx_name")]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        DateTime fDate;
        [Persistent(@"dt_date")]
        public DateTime Date
        {
            get { return fDate; }
            set { SetPropertyValue<DateTime>(nameof(Date), ref fDate, value); }
        }
        Publication fPublication;
        [Persistent(@"lnk_publication")]
        [Association(@"EditionReferencesPublication")]
        public Publication Publication
        {
            get { return fPublication; }
            set { SetPropertyValue<Publication>(nameof(Publication), ref fPublication, value); }
        }
        [Association(@"IssueReferencesEdition")]
        public XPCollection<Issue> Issues { get { return GetCollection<Issue>(nameof(Issues)); } }
    }

}
