//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SupportTicketDemo.DAL.Database
{

    [Persistent(@"tblIssue")]
    public partial class Issue : XPObject
    {
        Address fAddress;
        [Persistent(@"lnk_address")]
        [Association(@"IssueReferencesAddress")]
        public Address Address
        {
            get { return fAddress; }
            set { SetPropertyValue<Address>(nameof(Address), ref fAddress, value); }
        }
        Edition fEdition;
        [Persistent(@"lnk_edition")]
        [Association(@"IssueReferencesEdition")]
        public Edition Edition
        {
            get { return fEdition; }
            set { SetPropertyValue<Edition>(nameof(Edition), ref fEdition, value); }
        }
    }

}
