//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SupportTicketDemo.DAL.Database
{

    [Persistent(@"tblPermission")]
    public partial class Permission : XPObject
    {
        bool fEditable;
        [Persistent(@"yn_editable")]
        [ColumnDefaultValue(false)]
        public bool Editable
        {
            get { return fEditable; }
            set { SetPropertyValue<bool>(nameof(Editable), ref fEditable, value); }
        }
        Form fForm;
        [Persistent(@"lnk_form")]
        [Association(@"PermissionReferencesForm")]
        public Form Form
        {
            get { return fForm; }
            set { SetPropertyValue<Form>(nameof(Form), ref fForm, value); }
        }
        UserGroup fUserGroup;
        [Persistent(@"lnk_userGroup")]
        [Association(@"PermissionReferencesUserGroup")]
        public UserGroup UserGroup
        {
            get { return fUserGroup; }
            set { SetPropertyValue<UserGroup>(nameof(UserGroup), ref fUserGroup, value); }
        }
    }

}
