//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SupportTicketDemo.DAL.Database
{

    [Persistent(@"tblPublication")]
    public partial class Publication : XPObject
    {
        string fName;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"tx_name")]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        bool fActive;
        [Persistent(@"yn_active")]
        [ColumnDefaultValue(true)]
        public bool Active
        {
            get { return fActive; }
            set { SetPropertyValue<bool>(nameof(Active), ref fActive, value); }
        }
        bool fDeleted;
        [Persistent(@"yn_deleted")]
        [ColumnDefaultValue(false)]
        public bool Deleted
        {
            get { return fDeleted; }
            set { SetPropertyValue<bool>(nameof(Deleted), ref fDeleted, value); }
        }
        [Association(@"EditionReferencesPublication")]
        public XPCollection<Edition> Editions { get { return GetCollection<Edition>(nameof(Editions)); } }
        [Association(@"SubscriptionReferencesPublication")]
        public XPCollection<Subscription> Subscriptions { get { return GetCollection<Subscription>(nameof(Subscriptions)); } }
    }

}
