//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SupportTicketDemo.DAL.Database
{

    [Persistent(@"tblSubscriptionChange")]
    public partial class SubscriptionChange : XPObject
    {
        DateTime fDate;
        [Persistent(@"dt_date")]
        public DateTime Date
        {
            get { return fDate; }
            set { SetPropertyValue<DateTime>(nameof(Date), ref fDate, value); }
        }
        User fUser;
        [Persistent(@"lnk_user")]
        public User User
        {
            get { return fUser; }
            set { SetPropertyValue<User>(nameof(User), ref fUser, value); }
        }
        Subscription fSubscription;
        [Persistent(@"lnk_subscription")]
        [Association(@"SubscriptionChangeReferencesSubscription")]
        public Subscription Subscription
        {
            get { return fSubscription; }
            set { SetPropertyValue<Subscription>(nameof(Subscription), ref fSubscription, value); }
        }
        string fField;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"tx_field")]
        public string Field
        {
            get { return fField; }
            set { SetPropertyValue<string>(nameof(Field), ref fField, value); }
        }
        string fPrevious;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"tx_previous")]
        public string Previous
        {
            get { return fPrevious; }
            set { SetPropertyValue<string>(nameof(Previous), ref fPrevious, value); }
        }
        string fNew;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"tx_new")]
        public string New
        {
            get { return fNew; }
            set { SetPropertyValue<string>(nameof(New), ref fNew, value); }
        }
    }

}
