//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SupportTicketDemo.DAL.Database
{

    [Persistent(@"tblTag")]
    public partial class Tag : XPObject
    {
        string fName;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"tx_name")]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        [Association(@"AddressReferencesTag")]
        public XPCollection<Address> Addresses { get { return GetCollection<Address>(nameof(Addresses)); } }
    }

}
