//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SupportTicketDemo.DAL.Database
{

    [Persistent(@"tblUser")]
    public partial class User : XPObject
    {
        string fUsername;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"tx_username")]
        public string Username
        {
            get { return fUsername; }
            set { SetPropertyValue<string>(nameof(Username), ref fUsername, value); }
        }
        string fPassword;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"hs_password")]
        public string Password
        {
            get { return fPassword; }
            set { SetPropertyValue<string>(nameof(Password), ref fPassword, value); }
        }
        bool fActive;
        [Persistent(@"yn_active")]
        [ColumnDefaultValue(true)]
        public bool Active
        {
            get { return fActive; }
            set { SetPropertyValue<bool>(nameof(Active), ref fActive, value); }
        }
        bool fDeleted;
        [Persistent(@"yn_deleted")]
        [ColumnDefaultValue(false)]
        public bool Deleted
        {
            get { return fDeleted; }
            set { SetPropertyValue<bool>(nameof(Deleted), ref fDeleted, value); }
        }
        UserGroup fUserGroup;
        [Persistent(@"lnk_userGroup")]
        [Association(@"UserReferencesUserGroup")]
        public UserGroup UserGroup
        {
            get { return fUserGroup; }
            set { SetPropertyValue<UserGroup>(nameof(UserGroup), ref fUserGroup, value); }
        }
        [Association(@"WorkspaceReferencesUser")]
        public XPCollection<Workspace> Workspaces { get { return GetCollection<Workspace>(nameof(Workspaces)); } }
    }

}
