//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SupportTicketDemo.DAL.Database
{

    [Persistent(@"tblUserGroup")]
    public partial class UserGroup : XPObject
    {
        string fName;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"tx_name")]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fDescription;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"tx_description")]
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        [Association(@"UserReferencesUserGroup")]
        public XPCollection<User> Users { get { return GetCollection<User>(nameof(Users)); } }
        [Association(@"PermissionReferencesUserGroup")]
        public XPCollection<Permission> Permissions { get { return GetCollection<Permission>(nameof(Permissions)); } }
    }

}
