//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SupportTicketDemo.DAL.Database
{

    [Persistent(@"tblWorkspace")]
    public partial class Workspace : XPObject
    {
        string fName;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"tx_name")]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fForm;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"tx_form")]
        public string Form
        {
            get { return fForm; }
            set { SetPropertyValue<string>(nameof(Form), ref fForm, value); }
        }
        string fContent;
        [Size(SizeAttribute.Unlimited)]
        [Persistent(@"tx_content")]
        public string Content
        {
            get { return fContent; }
            set { SetPropertyValue<string>(nameof(Content), ref fContent, value); }
        }
        User fUser;
        [Persistent(@"lnk_user")]
        [Association(@"WorkspaceReferencesUser")]
        public User User
        {
            get { return fUser; }
            set { SetPropertyValue<User>(nameof(User), ref fUser, value); }
        }
        bool fPrivate;
        [Persistent(@"yn_private")]
        [ColumnDefaultValue(false)]
        public bool Private
        {
            get { return fPrivate; }
            set { SetPropertyValue<bool>(nameof(Private), ref fPrivate, value); }
        }
    }

}
